version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443' # Add HTTPS port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl # Add SSL volume
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network

  app:
    build: .
    restart: unless-stopped
    environment:
      - ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
